channels:
  breaking_news:
    - username: "CNNBrkNews"
      display_name: "CNN Breaking News"
    - username: "BBCNewsChannel"
      display_name: "BBC News (UK)"
  global_affairs:
    - username: "geopolitics_prime"
      display_name: "Geopolitics Prime"
    - username: "GeoPWatch"
      display_name: "Geopolitics Watch"
  health:
    - username: "RealHealthRanger"
      display_name: "Health Ranger"
  trump:
    - username: "real_DonaldJTrump"
      display_name: "Donald J. Trump"
  # tech:
  #   - username: "tech"
  #     display_name: "Startups & Ventures"
  # stock_market:
  #   - username: "trading"
  #     display_name: "Trade Watcher"